package assertions

import (
	"context"
	"database/sql"
	"fmt"
	"time"
)

// AssociationRunReport is the spec §10.9 per-run report: artifacts examined,
// candidates generated by method, resolution outcomes, lifecycle counts,
// newly proposed assertions, deterministic-vs-human decision counts, stale
// projections detected/repaired, and per-stage timing/errors. It must
// reconcile every examined artifact -- spec §16.3 item 17 -- which this
// package enforces structurally: CandidatesByMethod, ResolutionOutcomes, and
// LifecycleCounts are all built from the exact same row set as
// ArtifactsExamined, so their totals can never diverge from it (see
// Reconciles, which asserts that invariant rather than merely hoping it).
type AssociationRunReport struct {
	InputRecordID            int64
	ArtifactsExamined        int
	CandidatesByMethod       map[string]int
	ResolutionOutcomes       map[string]int
	LifecycleCounts          map[string]int
	DeferredByReason         map[string]int
	NewAssertions            int // distinct resulting_assertion_id values among this record's candidates
	DeterministicDecisions   int // accepted/rejected candidates decided without a human/LLM actor
	HumanDecisions           int // candidates whose method is 'human'
	StaleProjectionsFound    int
	StaleProjectionsRepaired int
	StageTimings             map[string]time.Duration
	StageErrors              map[string]string
}

// Reconciles reports whether every bucketed count sums back to
// ArtifactsExamined -- the observable form of spec §16.3 item 17's "without
// unaccounted candidates."
func (r AssociationRunReport) Reconciles() bool {
	sumMethod, sumOutcome, sumLifecycle := 0, 0, 0
	for _, n := range r.CandidatesByMethod {
		sumMethod += n
	}
	for _, n := range r.ResolutionOutcomes {
		sumOutcome += n
	}
	for _, n := range r.LifecycleCounts {
		sumLifecycle += n
	}
	return sumMethod == r.ArtifactsExamined &&
		sumOutcome == r.ArtifactsExamined &&
		sumLifecycle == r.ArtifactsExamined
}

// BuildAssociationRunReport queries the current state of every decision
// candidate tied to one input record (latest revision per logical identity,
// so a superseded earlier revision is not double-counted) and buckets it by
// method, resolution outcome, and lifecycle status.
func BuildAssociationRunReport(ctx context.Context, db *sql.DB, inputRecordID int64) (AssociationRunReport, error) {
	report := AssociationRunReport{
		InputRecordID:      inputRecordID,
		CandidatesByMethod: map[string]int{},
		ResolutionOutcomes: map[string]int{},
		LifecycleCounts:    map[string]int{},
		DeferredByReason:   map[string]int{},
	}
	if db == nil {
		return report, fmt.Errorf("db is nil")
	}

	const stmt = `
SELECT DISTINCT ON (logical_identity_key)
       method, resolution_outcome, status, dependency_fingerprint, resulting_assertion_id
FROM kb.semantic_decision_candidates
WHERE input_record_id = $1
ORDER BY logical_identity_key, revision DESC`
	rows, err := db.QueryContext(ctx, stmt, inputRecordID)
	if err != nil {
		return report, err
	}
	defer rows.Close()

	assertionIDs := map[int64]struct{}{}
	for rows.Next() {
		var method, status string
		var resolutionOutcome, dependencyFingerprint sql.NullString
		var resultingAssertionID sql.NullInt64
		if err := rows.Scan(&method, &resolutionOutcome, &status, &dependencyFingerprint, &resultingAssertionID); err != nil {
			return report, err
		}
		report.ArtifactsExamined++
		report.CandidatesByMethod[method]++

		outcome := "unresolved"
		if resolutionOutcome.Valid && resolutionOutcome.String != "" {
			outcome = resolutionOutcome.String
		}
		report.ResolutionOutcomes[outcome]++
		report.LifecycleCounts[status]++
		if status == StatusDeferred {
			reason := "unspecified"
			if dependencyFingerprint.Valid && dependencyFingerprint.String != "" {
				reason = dependencyFingerprint.String
			}
			report.DeferredByReason[reason]++
		}

		if method == "human" {
			report.HumanDecisions++
		} else if status == StatusAccepted || status == StatusRejected {
			report.DeterministicDecisions++
		}
		if resultingAssertionID.Valid {
			assertionIDs[resultingAssertionID.Int64] = struct{}{}
		}
	}
	if err := rows.Err(); err != nil {
		return report, err
	}
	report.NewAssertions = len(assertionIDs)

	// StaleProjectionsFound/Repaired are intentionally left zero here:
	// projection staleness is a global sweep (RepairStaleProjections), not
	// naturally scoped to one input record. RunPhaseD populates them from
	// that sweep's own result when it chooses to run one.
	return report, nil
}

// RunPhaseD runs all three DR8 Phase D stages for one input record in order
// -- normalize_assertions, associate_semantics, project_semantics -- timing
// each and capturing (not aborting on) per-stage errors, then builds the
// spec §10.9 reconciliation report. A stage error does not stop the
// following stages: normalize failures leave nothing for associate to find
// (a natural no-op), and associate failures still let project_semantics run
// against whatever was already accepted in a prior run.
func RunPhaseD(ctx context.Context, db *sql.DB, inputRecordID int64) (AssociationRunReport, error) {
	timings := map[string]time.Duration{}
	stageErrors := map[string]string{}

	runStage := func(name string, fn func() error) {
		start := time.Now()
		err := fn()
		timings[name] = time.Since(start)
		if err != nil {
			stageErrors[name] = err.Error()
		}
	}

	runStage("normalize_assertions", func() error {
		return NormalizeAllFamilies(ctx, db, inputRecordID)
	})

	runStage("associate_semantics", func() error {
		_, err := (AssociateSemantics{DB: db}).Run(ctx, inputRecordID)
		return err
	})

	runStage("project_semantics", func() error {
		_, err := (ProjectSemantics{DB: db}).Run(ctx, inputRecordID)
		return err
	})

	report, err := BuildAssociationRunReport(ctx, db, inputRecordID)
	if err != nil {
		return report, err
	}
	report.StageTimings = timings
	report.StageErrors = stageErrors
	return report, nil
}
