-- +goose Up
ALTER TABLE testbed.embedding_768
    ADD COLUMN IF NOT EXISTS time_ms BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS num_chars INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS num_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE testbed.embedding_1024
    ADD COLUMN IF NOT EXISTS time_ms BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS num_chars INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS num_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE testbed.embedding_1536
    ADD COLUMN IF NOT EXISTS time_ms BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS num_chars INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS num_tokens INTEGER NOT NULL DEFAULT 0;

-- +goose Down
ALTER TABLE testbed.embedding_1536
    DROP COLUMN IF EXISTS num_tokens,
    DROP COLUMN IF EXISTS num_chars,
    DROP COLUMN IF EXISTS time_ms;
ALTER TABLE testbed.embedding_1024
    DROP COLUMN IF EXISTS num_tokens,
    DROP COLUMN IF EXISTS num_chars,
    DROP COLUMN IF EXISTS time_ms;
ALTER TABLE testbed.embedding_768
    DROP COLUMN IF EXISTS num_tokens,
    DROP COLUMN IF EXISTS num_chars,
    DROP COLUMN IF EXISTS time_ms;
