-- +goose Up
-- The operational association-candidate lifecycle (ADR 2026072901 DR8; spec
-- 2026072702 §10.2-§10.6, §9.3). This is the Phase D counterpart to P2's
-- kb.ontology_candidates: a proposal for a referent link, term association,
-- assertion, occurrence, or profile selection, generated by one of the
-- spec §10.3 methods, resolved (spec §10.4) and adjudicated (spec §10.6)
-- before anything is persisted to an authoritative store.
--
-- logical_identity_key + revision mirrors kb.semantic_assertions: the latest
-- revision is current state. last_seen is bumped in place when reprocessing
-- produces the same payload_fingerprint (spec §16.3 item 2 "unchanged
-- payload records last_seen"); a changed payload_fingerprint creates a new
-- revision and supersedes the prior completed one instead of mutating it.
--
-- status uses the same operational vocabulary as kb.semantic_assertions
-- EXCEPT 'unsupported', which spec §9.3 defines as assertion-only ("an
-- accepted assertion -- last evidence lost --> unsupported"); a decision
-- candidate that loses its evidence is superseded or re-deferred, not
-- marked unsupported.
CREATE TABLE IF NOT EXISTS kb.semantic_decision_candidates (
    id                      BIGSERIAL PRIMARY KEY,
    logical_identity_key    TEXT NOT NULL,
    revision                INT NOT NULL DEFAULT 1,
    payload_fingerprint     TEXT NOT NULL,

    candidate_kind          TEXT NOT NULL CHECK (candidate_kind IN (
                                'referent', 'term_association', 'assertion',
                                'occurrence', 'profile_selection'
                             )),
    proposed_payload        JSONB NOT NULL,
    method                  TEXT NOT NULL CHECK (method IN (
                                'explicit_structured', 'deterministic_source_span',
                                'released_mapping', 'lexical_candidate',
                                'semantic_candidate', 'structural_candidate', 'human'
                             )),
    resolution_outcome      TEXT CHECK (resolution_outcome IS NULL OR resolution_outcome IN (
                                'matched', 'new_target_candidate', 'rejected', 'deferred'
                             )),
    resolution_reason       TEXT,

    source_artifact_type    TEXT,
    source_artifact_id      TEXT,
    source_line_spans       JSONB,
    confidence              DOUBLE PRECISION CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),

    status                  TEXT NOT NULL DEFAULT 'candidate' CHECK (status IN (
                                'candidate', 'in_review', 'accepted', 'rejected',
                                'deferred', 'superseded'
                             )),
    decision_reason         TEXT,
    dependency_fingerprint  TEXT,
    superseded_by           BIGINT REFERENCES kb.semantic_decision_candidates(id),
    resulting_assertion_id  BIGINT REFERENCES kb.semantic_assertions(id),

    last_seen               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    create_time             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    create_by               TEXT,
    modify_time              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    modify_by                TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_kb_semantic_decision_candidates_identity_revision
    ON kb.semantic_decision_candidates (logical_identity_key, revision);
CREATE INDEX IF NOT EXISTS idx_kb_semantic_decision_candidates_status
    ON kb.semantic_decision_candidates (status);
CREATE INDEX IF NOT EXISTS idx_kb_semantic_decision_candidates_identity_key
    ON kb.semantic_decision_candidates (logical_identity_key);
CREATE INDEX IF NOT EXISTS idx_kb_semantic_decision_candidates_source_artifact
    ON kb.semantic_decision_candidates (source_artifact_type, source_artifact_id);

-- +goose Down
DROP TABLE IF EXISTS kb.semantic_decision_candidates;
