-- +goose Up
-- prompt-extract-relations-v3.md adds subject_desc and object_desc: short
-- endpoint descriptions generated by the LLM alongside subject/object.
ALTER TABLE kb.relations ADD COLUMN IF NOT EXISTS subject_desc    TEXT;
ALTER TABLE kb.relations ADD COLUMN IF NOT EXISTS object_desc     TEXT;

-- +goose Down
ALTER TABLE kb.relations DROP COLUMN IF EXISTS object_desc;
ALTER TABLE kb.relations DROP COLUMN IF EXISTS subject_desc;
