-- +goose Up
-- ADR 2026093001 / openspec change i18n-paraglide-standard: NavRail menu labels
-- are now Paraglide messages (web/messages/{en,zh-cn}.json, keys nav_<id>).
-- Remove the label overrides that only repeat those defaults, so later edits to
-- the message files are not shadowed by stale rows. A row is changed only when
-- its label equals the new default exactly (an operator's own rename is kept);
-- the rows themselves stay, because they still carry visibility and access_role.
WITH defaults(page_key, entry_key, language, label) AS (VALUES
    ('development', 'dashboard', 'zh-cn', '仪表盘'),
    ('development', 'chat', 'zh-cn', '对话'),
    ('development', 'agents', 'zh-cn', '智能体'),
    ('resources', 'documents', 'zh-cn', '文档'),
    ('resources', 'docs-development', 'zh-cn', '开发'),
    ('resources', 'videos', 'zh-cn', '视频'),
    ('resources', 'videos-training', 'zh-cn', '培训'),
    ('development', 'cdm-editor', 'zh-cn', '智能编辑器'),
    ('development', 'flow', 'zh-cn', '流程'),
    ('development', 'prompt-optimizer', 'zh-cn', '提示词优化器'),
    ('development', 'ap-board', 'zh-cn', '看板'),
    ('development', 'sysadmin-resources', 'zh-cn', '资源'),
    ('development', 'sysadmin-resources-videos', 'zh-cn', '视频'),
    ('development', 'skills', 'zh-cn', '技能'),
    ('development', 'applications', 'zh-cn', '应用'),
    ('development', 'coding', 'zh-cn', '编程助手'),
    ('development', 'personal', 'zh-cn', '个人助手'),
    ('development', 'knowledge', 'zh-cn', '知识系统'),
    ('development', 'tools', 'zh-cn', '工具'),
    ('development', 'agent-platform', 'zh-cn', '智能体平台'),
    ('development', 'system-admin', 'zh-cn', '系统管理'),
    ('development', 'my-workspace', 'zh-cn', '我的工作台'),
    ('development', 'settings', 'zh-cn', '设置'),
    ('development', 'about', 'zh-cn', '关于'),
    ('development', 'doc-processor-dashboard', 'zh-cn', '文档处理器'),
    ('development', 'llm-activities', 'zh-cn', 'LLM 活动'),
    ('development', 'agents-my', 'zh-cn', '我的智能体'),
    ('development', 'agents-browse', 'zh-cn', '浏览智能体库'),
    ('development', 'agents-create', 'zh-cn', '创建智能体'),
    ('development', 'skills-all', 'zh-cn', '全部技能'),
    ('development', 'skills-active', 'zh-cn', '已启用'),
    ('development', 'skills-create', 'zh-cn', '新建技能'),
    ('development', 'apps-installed', 'zh-cn', '已安装'),
    ('development', 'apps-browse', 'zh-cn', '浏览'),
    ('development', 'apps-configure', 'zh-cn', '配置'),
    ('development', 'apps-generate-doc', 'zh-cn', '生成文档'),
    ('development', 'apps-document-review', 'zh-cn', '文档审核'),
    ('development', 'coding-review', 'zh-cn', '代码审查'),
    ('development', 'coding-gen', 'zh-cn', '代码生成'),
    ('development', 'coding-debug', 'zh-cn', '调试器'),
    ('development', 'personal-tasks', 'zh-cn', '任务'),
    ('development', 'personal-calendar', 'zh-cn', '日历'),
    ('development', 'personal-email', 'zh-cn', '邮件'),
    ('development', 'ke-research-topics', 'zh-cn', '研究课题'),
    ('development', 'kb-search-lab', 'zh-cn', '知识库检索实验室'),
    ('development', 'ap-agents', 'zh-cn', '智能体'),
    ('development', 'ap-projects', 'zh-cn', '项目'),
    ('development', 'sysadmin-jetstream-logs', 'zh-cn', 'JetStream 日志'),
    ('development', 'sysadmin-jetstream-events', 'zh-cn', 'JetStream 事件'),
    ('development', 'sysadmin-jetstream-subjects', 'zh-cn', 'JetStream 主题'),
    ('development', 'sysadmin-logs', 'zh-cn', '日志'),
    ('development', 'sysadmin-doc-proc-logs', 'zh-cn', '文档处理器日志'),
    ('development', 'sysadmin-llm-usage-logs', 'zh-cn', 'LLM 使用日志'),
    ('development', 'sysadmin-doc-review-logs', 'zh-cn', '文档审核日志'),
    ('development', 'sysadmin-llm-accounts', 'zh-cn', 'LLM 账户'),
    ('development', 'sysadmin-llm-model-profiles', 'zh-cn', '模型配置'),
    ('development', 'sysadmin-llm-models', 'zh-cn', 'LLM 模型'),
    ('development', 'sysadmin-db', 'zh-cn', '数据库维护'),
    ('development', 'sysadmin-db-consistency', 'zh-cn', '一致性检查'),
    ('development', 'sysadmin-db-maint-log', 'zh-cn', '维护日志'),
    ('development', 'sysadmin-db-resolve-ambiguous', 'zh-cn', '解决歧义对象'),
    ('development', 'sysadmin-users', 'zh-cn', '用户与权限'),
    ('development', 'sysadmin-user-management', 'zh-cn', '用户管理'),
    ('development', 'sysadmin-role-management', 'zh-cn', '角色管理'),
    ('development', 'sysadmin-access-controls', 'zh-cn', '访问控制'),
    ('development', 'diary', 'zh-cn', '日记'),
    ('development', 'sysadmin-keyword-normalization', 'en', 'Keyword Normalization'),
    ('development', 'sysadmin-keyword-rewrite-rules', 'en', 'Rewrite Rules'),
    ('development', 'sysadmin-keyword-normalization', 'zh-cn', '关键词规范化'),
    ('development', 'sysadmin-keyword-rewrite-rules', 'zh-cn', '重写规则'),
    ('development', 'jetstream', 'zh-cn', 'JetStream 消息队列'),
    ('development', 'sysadmin-llm', 'zh-cn', '大模型(LLM)'),
    ('development', 'knowledge-engineering', 'zh-cn', '知识工程'),
    ('development', 'sysadmin-doc-process-processors', 'en', 'Doc Processors'),
    ('development', 'sysadmin-doc-process-processors', 'zh-cn', '数据处理器(Doc Processor)'),
    ('development', 'sysadmin-doc-process-semantic-decision-candidates', 'en', 'Semantic Decision Candidates'),
    ('development', 'sysadmin-doc-process-semantic-decision-candidates', 'zh-cn', '语义决策备选项(Semantic Decision Candidate)'),
    ('development', 'sysadmin-doc-process-semantic-assertions', 'en', 'Semantic Assertions'),
    ('development', 'sysadmin-doc-process-semantic-assertions', 'zh-cn', '语义断言(Semantic Assertion)'),
    ('development', 'sysadmin-doc-process-assertion-evidence', 'en', 'Semantic Assertion Evidence'),
    ('development', 'sysadmin-doc-process-assertion-evidence', 'zh-cn', '语义断言依据'),
    ('development', 'sysadmin-doc-process-semantic-retry-queue', 'en', 'Semantic Retry Queue'),
    ('development', 'sysadmin-doc-process-semantic-retry-queue', 'zh-cn', '语义提取重试队列'),
    ('development', 'ontology', 'en', 'Ontology'),
    ('development', 'ontology', 'zh-cn', '本体'),
    ('development', 'ontology-doc-facets', 'en', 'Doc Facets'),
    ('development', 'ontology-doc-facets', 'zh-cn', '文档刻面(Facets)'),
    ('development', 'sysadmin-benchmark', 'en', 'Benchmark'),
    ('development', 'sysadmin-benchmark', 'zh-cn', '基准测试(Benchmark)'),
    ('development', 'sysadmin-doc-process-pipeline', 'en', 'Doc Process Pipeline'),
    ('development', 'sysadmin-page-config', 'zh-cn', '页面多语言配置'),
    ('development', 'agent-services', 'en', 'Knowledge Desk'),
    ('development', 'agent-services', 'zh-cn', '知识管理桌面'),
    ('development', 'sysadmin-schedules', 'en', 'Schedules'),
    ('development', 'sysadmin-schedules', 'zh-cn', '日程(Schedules)'),
    ('development', 'sysadmin-doc-process-pipeline', 'zh-cn', '数据处理流程(Pipeline)'),
    ('development', 'sysadmin-doc-process-dag', 'en', 'Doc Process DAG'),
    ('development', 'sysadmin-doc-process-dag', 'zh-cn', '数据处理流程图')
)
UPDATE kb.page_config pc
SET content = pc.content - 'label', updated_at = now(), updated_by = 'migration-20260930000001'
FROM defaults d
WHERE pc.page_key = d.page_key AND pc.entry_key = d.entry_key
  AND pc.language = d.language AND pc.content->>'label' = d.label;

-- +goose Down
-- The removed labels equal the Paraglide defaults, so the page renders the same
-- without them; nothing to restore.
SELECT 1;
