-- +goose Up
-- benchmark_run_id becomes a 'yyyymmdd_hhmmss' timestamp generated by the
-- extract-metrics-benchmark skill when a run is prepared. A run is identified by
-- (skill_name, skill_version, model_name, benchmark_run_id); runs are never
-- overwritten or extended (the skill's save refuses an existing run key).
ALTER TABLE testbed.metrics ALTER COLUMN benchmark_run_id TYPE TEXT USING benchmark_run_id::text;

-- Existing UUID runs take the local (America/Chicago) time of their first row;
-- the old UUID is kept in ext_info.legacy_benchmark_run_id.
UPDATE testbed.metrics m
   SET ext_info = m.ext_info || jsonb_build_object('legacy_benchmark_run_id', m.benchmark_run_id),
       benchmark_run_id = r.new_run_id
  FROM (SELECT benchmark_run_id,
               to_char(min(created_at) AT TIME ZONE 'America/Chicago', 'YYYYMMDD_HH24MISS') AS new_run_id
          FROM testbed.metrics
         WHERE benchmark_run_id !~ '^[0-9]{8}_[0-9]{6}$'
         GROUP BY benchmark_run_id) r
 WHERE m.benchmark_run_id = r.benchmark_run_id;

ALTER TABLE testbed.metrics
    ADD CONSTRAINT metrics_benchmark_run_id_format CHECK (benchmark_run_id ~ '^[0-9]{8}_[0-9]{6}$');
ALTER TABLE testbed.metrics DROP CONSTRAINT IF EXISTS metrics_input_record_id_benchmark_run_id_metric_id_key;
ALTER TABLE testbed.metrics
    ADD CONSTRAINT metrics_run_key_metric_id_key
    UNIQUE (skill_name, skill_version, model_name, benchmark_run_id, metric_id);

-- +goose Down
ALTER TABLE testbed.metrics DROP CONSTRAINT IF EXISTS metrics_run_key_metric_id_key;
ALTER TABLE testbed.metrics DROP CONSTRAINT IF EXISTS metrics_benchmark_run_id_format;
-- Restore legacy UUIDs; runs created after the Up migration get a fresh UUID per run key.
UPDATE testbed.metrics
   SET benchmark_run_id = ext_info->>'legacy_benchmark_run_id',
       ext_info = ext_info - 'legacy_benchmark_run_id'
 WHERE ext_info ? 'legacy_benchmark_run_id';
UPDATE testbed.metrics m
   SET benchmark_run_id = r.new_run_id
  FROM (SELECT skill_name, skill_version, model_name, benchmark_run_id,
               gen_random_uuid()::text AS new_run_id
          FROM testbed.metrics
         WHERE benchmark_run_id !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
         GROUP BY skill_name, skill_version, model_name, benchmark_run_id) r
 WHERE (m.skill_name, m.skill_version, m.model_name, m.benchmark_run_id)
     = (r.skill_name, r.skill_version, r.model_name, r.benchmark_run_id);
ALTER TABLE testbed.metrics ALTER COLUMN benchmark_run_id TYPE UUID USING benchmark_run_id::uuid;
ALTER TABLE testbed.metrics
    ADD CONSTRAINT metrics_input_record_id_benchmark_run_id_metric_id_key
    UNIQUE (input_record_id, benchmark_run_id, metric_id);
