-- +goose Up
ALTER TABLE IF EXISTS kb.chunks ADD COLUMN IF NOT EXISTS overlap_lines TEXT NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS kb.chunks ADD COLUMN IF NOT EXISTS normal_lines TEXT NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS kb.chunks ADD COLUMN IF NOT EXISTS chunk_lines TEXT NOT NULL DEFAULT '';

-- +goose Down
ALTER TABLE IF EXISTS kb.chunks DROP COLUMN IF EXISTS chunk_lines;
ALTER TABLE IF EXISTS kb.chunks DROP COLUMN IF EXISTS normal_lines;
ALTER TABLE IF EXISTS kb.chunks DROP COLUMN IF EXISTS overlap_lines;
