-- Lossless Semantic Processing (ADR 2026081801) -- clear doc-processor-generated
-- data only, for a clean re-run of extract_metrics / extract_provisions /
-- normalize_assertions / associate_semantics / project_semantics against real
-- documents (task 7.7 scoping session, 2026-08-20).
--
-- Scope, reviewed against the live schema and current data before writing this:
--
--   Section A -- wholesale-cleared (pure processor output, no curated data ever
--   lives here). Deleted in FK-dependency order (children before parents).
--
--   Section B -- scoped delete on kb.ontology_term_headers /
--   kb.ontology_class_contract_revisions (+ 2 capability-tracking dependents).
--   These tables hold BOTH curated vocabulary (4,213 QUDT terms, 131
--   ontology-seed curated classes as of 2026-08-20) and provisional classes
--   metric_lossless_writer can create at runtime (provisionalMetricClassTermID /
--   resolveOrCreateMetricClass in metric_lossless_writer.go). Only rows created
--   by that writer (create_by = 'metric_lossless_writer') are removed -- curated
--   rows are untouched. provision_lossless_writer never touches these tables
--   (provisions need no class resolution), so no second create_by value exists
--   to filter on today; if a future family's writer (task 7.7) starts creating
--   provisional classes too, add its writer name to Section B's filter.
--
-- Deliberately NOT touched, and why:
--   kb.metric_value_range_type_map   -- curated admin mapping decisions (63
--                                        approved / 5 proposed / 7 ambiguous as
--                                        of 2026-08-20); re-running extract_metrics
--                                        should re-observe these idempotently,
--                                        not need a reset.
--   kb.semantic_adapter_compliance   -- DR13 certification audit trail (task
--                                        6.9/7.6's passing conformance results).
--   kb.metric_support_cleanup_audit  -- historical remediation audit trail
--                                        (task 6.2's one-time backfill), not
--                                        regenerated by any processor run.
--   kb.assertion_relations           -- FK to kb.semantic_assertions exists,
--                                        but no production code currently
--                                        writes to this table (grepped: zero
--                                        non-test callers of RelationsStore).
--                                        Included in Section A's delete order
--                                        anyway since it sits between
--                                        semantic_assertions and its
--                                        dependents -- a no-op today.
--   kb.artifact_objects              -- self-cleans: extract_metrics /
--                                        extract_provisions delete-and-replace
--                                        per (source_record_id, artifact_type)
--                                        on every run (ReplaceObjectsForRecord).
--   kb.ontology_term_redirects,
--   kb.ontology_term_revisions       -- not written by any processor in this
--                                        ADR today (ADR 2026081701 dependency,
--                                        not yet implemented); no provisional
--                                        rows exist there to clean up.
--   Curated ontology vocabulary itself -- everything in ontology_term_headers /
--                                        ontology_class_contract_revisions NOT
--                                        matching Section B's create_by filter.
--
--   kb.ontology_class_resolution_decisions,
--   kb.ontology_class_resolution_alternatives,
--   kb.semantic_claim_identities      -- NOT a scoping choice: these three are
--                                        database-enforced append-only/immutable
--                                        (BEFORE DELETE OR UPDATE triggers
--                                        kb_class_resolution_decisions_immutable,
--                                        kb_class_resolution_alternatives_immutable,
--                                        kb_semantic_claim_identities_immutable --
--                                        all raise "... is append-only"/"...
--                                        is immutable" unconditionally).
--                                        Discovered by dry-running this script
--                                        in a rolled-back transaction before
--                                        handing it over -- an earlier draft
--                                        tried to clear all three and failed.
--                                        This is by design (DR2/DR10's claim
--                                        and class-decision registries must
--                                        survive a re-run so re-processing the
--                                        same document converges onto the same
--                                        claim/class identity instead of
--                                        minting new ones). Practical effect on
--                                        the verification plan: re-running
--                                        against a document already processed
--                                        once (doc 416) will find its existing
--                                        claim identities and class-resolution
--                                        history still there and reuse them
--                                        (ClaimIdentityStore.FindOrCreateShadow
--                                        / ClassResolutionDecisionStore
--                                        .RecordIfChanged are both idempotent
--                                        find-or-create/no-op-if-unchanged, not
--                                        create-always) -- this is correct
--                                        behavior, not a leftover-data bug.
--                                        Checked as of 2026-08-20: none of the
--                                        60 existing kb.ontology_class_
--                                        resolution_decisions rows set
--                                        source_assertion_id (all NULL), so
--                                        Section A's kb.semantic_assertions
--                                        delete is not blocked by this today --
--                                        if a future writer version starts
--                                        populating that column, deleting a
--                                        referenced assertion row would fail
--                                        loudly (safe: the whole transaction
--                                        rolls back) rather than silently
--                                        leaving an orphaned reference.
--
-- Run with: PGDATABASE=miner psql -f clear-processor-artifacts.sql
-- (or point at whichever database you're about to reprocess against -- this
-- script is not database-name-specific).
--
-- Safe to re-run: every statement is idempotent (DELETE of already-absent rows
-- is a no-op). Wrapped in one transaction so a failure anywhere rolls back
-- everything -- nothing is left partially cleared.

BEGIN;

-- ============================================================
-- Section A: wholesale clear -- pure processor output.
-- Order matters: children before parents (see FK graph in the
-- session that authored this script; re-derive with \d if this
-- script is reused after the schema changes).
-- ============================================================

DELETE FROM kb.semantic_retry_queue;

DELETE FROM kb.ontology_observed_class_attribute_distributions;
DELETE FROM kb.ontology_observed_class_profile_exceptions;
DELETE FROM kb.ontology_observed_class_profile_examples;
DELETE FROM kb.ontology_observed_class_attribute_observations;
DELETE FROM kb.ontology_observed_class_profiles;

-- kb.ontology_class_resolution_decisions / _alternatives are NOT cleared here
-- -- see the immutability note above.

DELETE FROM kb.semantic_processing_findings;
DELETE FROM kb.unresolved_semantic_occurrences;
DELETE FROM kb.semantic_processing_outcomes;

DELETE FROM kb.assertion_evidence;
DELETE FROM kb.assertion_relations;
DELETE FROM kb.semantic_decision_candidates;

DELETE FROM kb.semantic_assertions;

-- kb.semantic_claim_identities is NOT cleared here -- see the immutability
-- note above.

DELETE FROM kb.metrics;
DELETE FROM kb.provisions;

DELETE FROM kb.projection_state;

-- ============================================================
-- Section B: scoped delete -- provisional ontology classes only.
-- Must run AFTER Section A: kb.semantic_assertions holds NOT VALID
-- FKs into both tables below (instance_of_term_id,
-- normalized_against_contract_revision_id) that are still enforced
-- for deletes on the referenced side.
-- ============================================================

-- Break the circular term_headers <-> contract_revisions reference
-- before deleting either side.
UPDATE kb.ontology_term_headers
   SET current_contract_revision_id = NULL
 WHERE create_by = 'metric_lossless_writer';

UPDATE kb.ontology_class_contract_revisions
   SET supersedes_revision_id = NULL
 WHERE create_by = 'metric_lossless_writer';

DELETE FROM kb.ontology_class_capability_validation_results
 WHERE contract_revision_id IN (
   SELECT id FROM kb.ontology_class_contract_revisions
   WHERE create_by = 'metric_lossless_writer'
 );

DELETE FROM kb.ontology_class_contract_capabilities
 WHERE contract_revision_id IN (
   SELECT id FROM kb.ontology_class_contract_revisions
   WHERE create_by = 'metric_lossless_writer'
 );

DELETE FROM kb.ontology_class_contract_revisions
 WHERE create_by = 'metric_lossless_writer';

DELETE FROM kb.ontology_term_headers
 WHERE create_by = 'metric_lossless_writer';

COMMIT;
