<script lang="ts">
	import { m } from '$lib/paraglide/messages.js';
 import { onMount } from 'svelte';
 import { listRewriteRules, listRewriteScopes, createRewriteRule, updateRewriteRule, toggleRewriteRule, validateRewriteDraft, type RewriteRule } from './keyword-rewrite-rules-client';
 let { darkMode = true }: { darkMode?: boolean } = $props();
 let rules = $state<RewriteRule[]>([]), scopes = $state<string[]>(['_']), loading = $state(true), error = $state('');
 let query = $state(''), scope = $state(''), enabled = $state('all'), modal = $state(false), editing = $state(false), saving = $state(false), formError = $state('');
 let draft = $state({ rule_id: '', pattern: '', replacement: '', scope: '_', provenance: 'human:', enabled: false });
 const colors = $derived({ bg: darkMode ? '#171B26' : '#F2F4F7', card: darkMode ? '#1F2333' : '#fff', text: darkMode ? '#E2E8F0' : '#111827', muted: darkMode ? '#94A3B8' : '#6B7280', border: darkMode ? '#2D3348' : '#E4E6EB', accent: darkMode ? '#A5B4FC' : '#4F46E5' });
 let filtered = $derived(rules.filter((r) => (!query || [r.rule_id,r.pattern,r.replacement,r.provenance].some((v) => v.toLowerCase().includes(query.toLowerCase()))) && (!scope || r.scope === scope) && (enabled === 'all' || String(r.enabled) === enabled)));
 async function load() { loading = true; error = ''; try { [rules, scopes] = await Promise.all([listRewriteRules(), listRewriteScopes()]); } catch (e) { error = e instanceof Error ? e.message : m.keyword_rewrite_rules_unable_to_load_rewrite_rules(); } finally { loading = false; } }
 function openNew() { editing = false; formError = ''; draft = { rule_id: '', pattern: '', replacement: '', scope: '_', provenance: 'human:', enabled: false }; modal = true; }
 function openEdit(rule: RewriteRule) { editing = true; formError = ''; draft = { rule_id: rule.rule_id, pattern: rule.pattern, replacement: rule.replacement, scope: rule.scope, provenance: rule.provenance, enabled: rule.enabled }; modal = true; }
 async function save() { formError = validateRewriteDraft(draft, editing) ?? ''; if (formError) return; saving = true; try { if (editing) await updateRewriteRule(draft.rule_id, { pattern: draft.pattern, replacement: draft.replacement, scope: draft.scope, provenance: draft.provenance, enabled: draft.enabled }); else await createRewriteRule(draft); modal = false; await load(); } catch (e) { formError = e instanceof Error ? e.message : m.keyword_rewrite_rules_unable_to_save_rule(); } finally { saving = false; } }
 async function toggle(rule: RewriteRule) { if (!confirm((rule.enabled ? m.keyword_rewrite_rules_disable_rule : m.keyword_rewrite_rules_enable_rule)({ rule_id: rule.rule_id }))) return; try { await toggleRewriteRule(rule.rule_id, !rule.enabled); await load(); } catch (e) { error = e instanceof Error ? e.message : m.keyword_rewrite_rules_unable_to_change_rule_status(); } }
 onMount(load);
</script>

<div class="page" style={`background:${colors.bg};color:${colors.text}`}>
 <section class="card intro" style={`background:${colors.card};border-color:${colors.border}`}>
  <div><h1>{m.keyword_rewrite_rules_rewrite_rules()}</h1><p>{m.keyword_rewrite_rules_exact_whole_input_scope_specific()}</p><small>{m.keyword_rewrite_rules_user_manual_keyword_rewrite()}</small></div>
  <div class="actions"><button onclick={openNew}>{m.keyword_rewrite_rules_new_rule()}</button><button class="secondary" onclick={load}>{m.keyword_rewrite_rules_refresh()}</button></div>
 </section>
 <section class="card" style={`background:${colors.card};border-color:${colors.border}`}>
  <div class="filters"><input aria-label={m.keyword_rewrite_rules_search_rules()} bind:value={query} placeholder={m.keyword_rewrite_rules_search_id_pattern_replacement_provenance()} /><select bind:value={scope}><option value="">{m.keyword_rewrite_rules_all_scopes()}</option>{#each scopes as item}<option value={item}>{item}</option>{/each}</select><select bind:value={enabled}><option value="all">{m.keyword_rewrite_rules_all_statuses()}</option><option value="true">{m.keyword_rewrite_rules_enabled()}</option><option value="false">{m.keyword_rewrite_rules_disabled()}</option></select></div>
  {#if loading}<div class="state">{m.keyword_rewrite_rules_loading_rewrite_rules()}</div>{:else if error}<div class="state error">{error}</div>{:else}<div class="table-wrap"><table><thead><tr><th>{m.keyword_rewrite_rules_rule_id()}</th><th>{m.keyword_rewrite_rules_pattern()}</th><th>{m.keyword_rewrite_rules_replacement()}</th><th>{m.keyword_rewrite_rules_scope()}</th><th>{m.keyword_rewrite_rules_status()}</th><th>{m.keyword_rewrite_rules_provenance()}</th><th>{m.keyword_rewrite_rules_modified()}</th><th></th></tr></thead><tbody>{#each filtered as rule}<tr><td>{rule.rule_id}</td><td class="literal">{rule.pattern}</td><td class="literal">{rule.replacement}</td><td>{rule.scope}</td><td><button class:enabled={rule.enabled} class="status" onclick={() => toggle(rule)}>{rule.enabled ? m.keyword_rewrite_rules_enabled() : m.keyword_rewrite_rules_disabled()}</button></td><td>{rule.provenance}</td><td>{new Date(rule.modify_time).toLocaleString()}</td><td><button class="link" onclick={() => openEdit(rule)}>{m.keyword_rewrite_rules_edit()}</button></td></tr>{:else}<tr><td colspan="8" class="state">{m.keyword_rewrite_rules_no_rewrite_rules_match_these()}</td></tr>{/each}</tbody></table></div>{/if}
 </section>
</div>

{#if modal}<div class="backdrop" role="presentation" onclick={(e) => e.target === e.currentTarget && (modal = false)}><div class="modal" role="dialog" aria-modal="true" aria-label={editing ? m.keyword_rewrite_rules_edit_rewrite_rule() : m.keyword_rewrite_rules_new_rewrite_rule()} style={`background:${colors.card};color:${colors.text};border-color:${colors.border}`}><div class="modal-head"><h2>{editing ? m.keyword_rewrite_rules_edit_rule() : m.keyword_rewrite_rules_new_rule()}</h2><button class="link" onclick={() => (modal = false)}>{m.keyword_rewrite_rules_close()}</button></div><div class="columns"><div class="form">{#if editing}<label>{m.keyword_rewrite_rules_rule_id()}<input bind:value={draft.rule_id} disabled /></label>{:else}<label>{m.keyword_rewrite_rules_rule_id()}<input bind:value={draft.rule_id} /></label>{/if}<label>{m.keyword_rewrite_rules_pattern()}<input bind:value={draft.pattern} /></label><label>{m.keyword_rewrite_rules_replacement()}<input bind:value={draft.replacement} /></label><label>{m.keyword_rewrite_rules_scope()}<select bind:value={draft.scope}>{#each scopes as item}<option value={item}>{item}</option>{/each}<option value="__custom">{m.keyword_rewrite_rules_custom()}</option></select></label>{#if draft.scope === '__custom'}<label>{m.keyword_rewrite_rules_custom_scope()}<input bind:value={draft.scope} placeholder={m.keyword_rewrite_rules_required_scope()} /></label>{/if}<label>{m.keyword_rewrite_rules_provenance()}<input bind:value={draft.provenance} /></label><label class="check"><input type="checkbox" bind:checked={draft.enabled} /> {m.keyword_rewrite_rules_enabled()}</label></div><aside class="preview"><h3>{m.keyword_rewrite_rules_hypothetical_preview()}</h3>{#if !draft.pattern.trim() || !draft.replacement.trim()}<p>{m.keyword_rewrite_rules_enter_a_pattern_and_replacement()}</p>{:else}<p class="literal">{draft.pattern} → {draft.replacement}</p><p>{m.keyword_rewrite_rules_exact_scope()} <strong>{draft.scope}</strong><br />{m.keyword_rewrite_rules_status_2({ value: draft.enabled ? m.keyword_rewrite_rules_enabled_lower() : m.keyword_rewrite_rules_disabled_draft() })}</p><p>{m.keyword_rewrite_rules_whole_string_case_sensitive_single()}</p>{/if}</aside></div>{#if formError}<div class="error">{formError}</div>{/if}<div class="modal-actions"><button class="secondary" onclick={() => (modal = false)}>{m.keyword_rewrite_rules_cancel()}</button><button onclick={save} disabled={saving}>{saving ? m.keyword_rewrite_rules_saving() : m.keyword_rewrite_rules_save_rule()}</button></div></div></div>{/if}

<style>
 .page{min-height:100%;padding:24px;display:grid;gap:16px;font:13px system-ui}.card{border:1px solid;border-radius:12px;padding:20px;box-shadow:0 4px 18px #0001}.intro{display:flex;justify-content:space-between;gap:16px}.intro h1{margin:0 0 8px;font-size:22px}.intro p{margin:0 0 10px;color:#94a3b8}.actions,.filters,.modal-actions{display:flex;gap:8px;align-items:center}.filters{margin-bottom:16px}.filters input{flex:1}input,select{border:1px solid #64748b;border-radius:7px;padding:8px;background:transparent;color:inherit;min-width:0}button{border:0;border-radius:7px;padding:8px 12px;background:#6366f1;color:white;cursor:pointer}.secondary{background:transparent;border:1px solid #64748b;color:inherit}.link{background:transparent;color:#a5b4fc;padding:4px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;white-space:nowrap}th,td{text-align:left;border-bottom:1px solid #64748b44;padding:11px 8px}.literal{font-family:ui-monospace,monospace}.status{background:#64748b;color:white;padding:4px 8px}.status.enabled{background:#15803d}.state{text-align:center;padding:42px;color:#94a3b8}.error{color:#fca5a5;margin:12px 0}.backdrop{position:fixed;inset:0;background:#0008;display:grid;place-items:center;padding:20px;z-index:20}.modal{max-width:850px;width:100%;border:1px solid;border-radius:12px;padding:22px}.modal-head{display:flex;justify-content:space-between;align-items:center}.modal-head h2{margin:0}.columns{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin:18px 0}.form{display:grid;gap:12px}.form label{display:grid;gap:5px}.check{display:flex!important;align-items:center;grid-template-columns:auto 1fr}.preview{border:1px solid #64748b55;border-radius:10px;padding:16px;background:#64748b11}.preview h3{margin-top:0}@media(max-width:700px){.intro,.columns{display:block}.actions{margin-top:16px}.preview{margin-top:18px}}
</style>
