export type MetricWikiCopy = {
	eyebrow: string;
	sourcePrefix: string;
	definition: string;
	background: string;
	howUsed: string;
	choosingValues: string;
	generalBackground: string;
	generalBackgroundTitle: string;
	inThisCorpus: string;
	grounded: string;
	sourceLabel: string;
	relatedMetrics: string;
	value: string;
	unit: string;
	rangeType: string;
	thresholdOrTarget: string;
	measurementFrequency: string;
	subject: string;
	confidence: string;
	noStructuredValues: string;
	buildingTitle: string;
	buildingSub: string;
	loadErrorTitle: string;
	retry: string;
	metricIdLabel: string;
	generatedByPrefix: string;
	freshlyGenerated: string;
	artifactRecord: string;
	loadingGroundedRecord: string;
	fetchingGroundedRecord: string;
	coreFields: string;
	jsonFields: string;
	record: string;
};

const EN_COPY: MetricWikiCopy = {
	eyebrow: 'SemOS metric',
	sourcePrefix: 'from',
	definition: 'Definition',
	background: 'Background',
	howUsed: 'How it is used',
	choosingValues: 'Choosing values',
	generalBackground: 'general background',
	generalBackgroundTitle: 'General background, not specific to this corpus',
	inThisCorpus: 'In this corpus',
	grounded: 'grounded',
	sourceLabel: 'Source:',
	relatedMetrics: 'Related metrics',
	value: 'Value',
	unit: 'Unit',
	rangeType: 'Range type',
	thresholdOrTarget: 'Threshold / target',
	measurementFrequency: 'Measurement frequency',
	subject: 'Subject',
	confidence: 'Confidence',
	noStructuredValues: 'No structured values recorded.',
	buildingTitle: 'Building this page…',
	buildingSub: 'Compiling what the knowledge base knows about this metric.',
	loadErrorTitle: 'Could not load this page',
	retry: 'Try again',
	metricIdLabel: 'metric_id',
	generatedByPrefix: 'generated by',
	freshlyGenerated: 'freshly generated',
	artifactRecord: 'Artifact Record',
	loadingGroundedRecord: 'Loading grounded record…',
	fetchingGroundedRecord: 'Fetching grounded record…',
	coreFields: 'Core Fields',
	jsonFields: 'JSON Fields',
	record: 'Record'
};

const ZH_CN_COPY: MetricWikiCopy = {
	eyebrow: 'SemOS 指标',
	sourcePrefix: '来源',
	definition: '定义',
	background: '背景',
	howUsed: '使用方式',
	choosingValues: '取值说明',
	generalBackground: '通用背景',
	generalBackgroundTitle: '通用背景，并非仅针对当前语料',
	inThisCorpus: '在本语料中',
	grounded: '有据可依',
	sourceLabel: '来源：',
	relatedMetrics: '相关指标',
	value: '值',
	unit: '单位',
	rangeType: '范围类型',
	thresholdOrTarget: '阈值 / 目标',
	measurementFrequency: '测量频率',
	subject: '主题',
	confidence: '置信度',
	noStructuredValues: '暂无结构化字段。',
	buildingTitle: '正在构建页面…',
	buildingSub: '正在整理知识库中关于该指标的信息。',
	loadErrorTitle: '无法加载此页面',
	retry: '重试',
	metricIdLabel: '指标 ID',
	generatedByPrefix: '生成模型',
	freshlyGenerated: '刚刚生成',
	artifactRecord: '制品记录',
	loadingGroundedRecord: '正在加载有据可依的记录…',
	fetchingGroundedRecord: '正在获取有据可依的记录…',
	coreFields: '核心字段',
	jsonFields: 'JSON 字段',
	record: '记录'
};

export function metricWikiCopyForLang(lang?: string): MetricWikiCopy {
	switch ((lang ?? '').trim().toLowerCase()) {
		case 'zh-cn':
			return ZH_CN_COPY;
		default:
			return EN_COPY;
	}
}
