<script lang="ts">
	import { onMount } from 'svelte';
	import RefreshCwIcon from '@lucide/svelte/icons/refresh-cw';
	import PlusIcon from '@lucide/svelte/icons/plus';
	import { listAssertions, saveAssertion, transitionAssertion, deferAssertion, retryAssertion, type Assertion, type AssertionFilters, type AssertionSortKey } from './semantic-assertions-client';
	let { darkMode = true }: { darkMode: boolean } = $props();
	let bg=$derived(darkMode?'#171B26':'#F2F4F7'), card=$derived(darkMode?'#1F2333':'#FFFFFF'), surface=$derived(darkMode?'#252A3A':'#ECEEF2'), border=$derived(darkMode?'#2D3348':'#E4E6EB'), accent=$derived(darkMode?'#818CF8':'#6366F1'), text=$derived(darkMode?'#E2E8F0':'#111827'), muted=$derived(darkMode?'#94A3B8':'#6B7280'), danger=$derived(darkMode?'#F87171':'#DC2626');
	let rows=$state<Assertion[]>([]), total=$state(0), page=$state(1), loading=$state(false), error=$state(''), info=$state(''), selected=$state<Assertion|null>(null), showCreate=$state(false), saving=$state(false), reason=$state(''), dependency=$state(''), sortBy=$state<AssertionSortKey|''>('modified'), sortDir=$state<'asc'|'desc'>('desc'), pageSize=$state(50);
	const pageSizeOptions = [25, 50, 100, 200];
	const sortableHeaders: { key: AssertionSortKey; label: string }[] = [
		{ key: 'identity', label: 'Identity' },
		{ key: 'subject', label: 'Subject' },
		{ key: 'predicate', label: 'Predicate' },
		{ key: 'status', label: 'Status' },
		{ key: 'modified', label: 'Modified' }
	];
	let filters=$state<AssertionFilters>({status:'',logical_identity:'',subject_ref_kind:'',subject_ref_id:'',predicate_term_id:'',object_ref_id:'',subject_object_id:'',latest_only:true});
	let form=$state({revision:0,logical_identity_key:'',subject_ref_kind:'object_node',subject_ref_id:'',predicate_term_id:'',object_ref_kind:'',object_ref_id:'',object_literal:'',polarity:'positive',confidence:'',raw_text:''});
	const statuses=['candidate','in_review','accepted','rejected','deferred','superseded','unsupported']; const kinds=['object_node','ontology_term','assertion','artifact','literal','keyword_concept'];
	async function load(){loading=true;error='';try{const r=await listAssertions(filters,page,pageSize,sortBy||undefined,sortDir);rows=r.results;total=r.total;}catch(e){error=e instanceof Error?e.message:String(e)}finally{loading=false}}
	function apply(){page=1;load()} function changePageSize(value:string){pageSize=Number(value);page=1;load()} function toggle(key:AssertionSortKey){if(sortBy===key)sortDir=sortDir==='asc'?'desc':'asc';else{sortBy=key;sortDir='asc'}page=1;load()}
	function json(v:unknown){try{return JSON.stringify(v,null,2)}catch{return String(v)}} function time(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString()}
	function can(a:Assertion,to:string){return (a.status==='candidate'&&['in_review','rejected'].includes(to))||(a.status==='in_review'&&['accepted','rejected'].includes(to))||(a.status==='accepted'&&['unsupported','superseded'].includes(to))||(a.status==='unsupported'&&to==='accepted')}
	async function transition(to:string){if(!selected)return;saving=true;try{selected=await transitionAssertion(selected.id,{to,reason});info=`Assertion #${selected.id} moved to ${to}.`;await load()}catch(e){error=e instanceof Error?e.message:String(e)}finally{saving=false}}
	async function defer(){if(!selected||!dependency.trim())return;saving=true;try{selected=await deferAssertion(selected.id,{dependency_fingerprint:dependency,reason});info='Assertion deferred.';await load()}catch(e){error=e instanceof Error?e.message:String(e)}finally{saving=false}}
	async function retry(){if(!selected||!dependency.trim())return;saving=true;try{selected=await retryAssertion(selected.id,{dependency_fingerprint:dependency});info='Deferred assertion retried.';await load()}catch(e){error=e instanceof Error?e.message:String(e)}finally{saving=false}}
	async function create(){saving=true;try{const payload:any={...form,confidence:form.confidence?Number(form.confidence):undefined,object_literal:form.object_literal?JSON.parse(form.object_literal):undefined};await saveAssertion(payload);showCreate=false;info='Assertion revision created.';await load()}catch(e){error=e instanceof Error?e.message:String(e)}finally{saving=false}}
	function newRevision(){if(!selected)return;form={revision:selected.revision,logical_identity_key:selected.logical_identity_key,subject_ref_kind:selected.subject_ref_kind,subject_ref_id:selected.subject_ref_id,predicate_term_id:selected.predicate_term_id,object_ref_kind:selected.object_ref_kind||'',object_ref_id:selected.object_ref_id||'',object_literal:selected.object_literal?json(selected.object_literal):'',polarity:selected.polarity,confidence:selected.confidence===undefined?'':String(selected.confidence),raw_text:selected.raw_text||''};showCreate=true}
	onMount(load);
</script>

<div class="h-full space-y-4 overflow-auto p-6" style="background:{bg}">
	<div class="rounded-xl p-5" style="background:{card};border:1px solid {border}"><div class="flex flex-wrap items-start justify-between gap-3"><div><h2 style="font-size:18px;font-weight:600;color:{text}">Semantic Assertions</h2><p style="font-size:13px;color:{muted};margin-top:2px">Lifecycle-safe administration of <code style="color:{accent}">kb.semantic_assertions</code>.</p></div><div class="flex gap-2"><button onclick={()=>showCreate=true} class="cursor-pointer rounded-lg px-3 py-2 text-sm" style="background:{accent};color:white"><PlusIcon class="inline h-4 w-4" /> New Assertion</button><button onclick={load} disabled={loading} class="cursor-pointer rounded-lg px-3 py-2 text-sm" style="background:{surface};color:{text};border:1px solid {border}"><RefreshCwIcon class="inline h-4 w-4" /> Refresh</button></div></div></div>
	<div class="rounded-xl p-5" style="background:{card};border:1px solid {border}"><div class="grid gap-3" style="grid-template-columns:repeat(auto-fill,minmax(160px,1fr))"><label>Status<select bind:value={filters.status} class="w-full rounded px-2 py-1.5 text-sm" style="background:{surface};color:{text};border:1px solid {border}"><option value="">Any</option>{#each statuses as s}<option>{s}</option>{/each}</select></label><label>Identity<input bind:value={filters.logical_identity} class="w-full rounded px-2 py-1.5 text-sm" style="background:{surface};color:{text};border:1px solid {border}" /></label><label>Subject Kind<select bind:value={filters.subject_ref_kind} class="w-full rounded px-2 py-1.5 text-sm" style="background:{surface};color:{text};border:1px solid {border}"><option value="">Any</option>{#each kinds as k}<option>{k}</option>{/each}</select></label><label>Subject ID<input bind:value={filters.subject_ref_id} class="w-full rounded px-2 py-1.5 text-sm" style="background:{surface};color:{text};border:1px solid {border}" /></label><label>Predicate<input bind:value={filters.predicate_term_id} class="w-full rounded px-2 py-1.5 text-sm" style="background:{surface};color:{text};border:1px solid {border}" /></label><label>Object ID<input bind:value={filters.object_ref_id} class="w-full rounded px-2 py-1.5 text-sm" style="background:{surface};color:{text};border:1px solid {border}" /></label></div><label class="mt-3 flex items-center gap-2 text-sm" style="color:{muted}"><input type="checkbox" bind:checked={filters.latest_only} onchange={apply}/> Latest revision only</label><button onclick={apply} class="mt-3 cursor-pointer rounded-lg px-3 py-2 text-sm" style="background:{accent};color:white">Apply Filters</button></div>
	{#if error}<div class="rounded-xl p-4" style="background:{danger}20;color:{danger}">{error}</div>{/if}{#if info}<div class="rounded-xl p-4" style="background:{accent}20;color:{accent}">{info}</div>{/if}
	<div class="overflow-hidden rounded-xl" style="background:{card};border:1px solid {border}"><div class="flex justify-between px-5 py-3 text-sm" style="border-bottom:1px solid {border};color:{muted}">Total: {total}<div class="flex items-center gap-2"><button onclick={()=>{if(page>1){page--;load()}}} disabled={page<=1||loading}>‹</button><label class="flex items-center gap-2"><span>Page Size</span><select value={pageSize} onchange={(event)=>changePageSize((event.currentTarget as HTMLSelectElement).value)} disabled={loading} class="rounded px-2 py-1" style="background:{surface};color:{text};border:1px solid {border}">{#each pageSizeOptions as option}<option value={option}>{option}</option>{/each}</select></label> Page {page} of {Math.max(1,Math.ceil(total/pageSize))}<button onclick={()=>{if(page<Math.ceil(total/pageSize)){page++;load()}}} disabled={page>=Math.ceil(total/pageSize)||loading}>›</button></div></div>{#if loading}<div class="p-8 text-center" style="color:{muted}">Loading…</div>{:else}<div class="overflow-auto"><table class="w-full text-left text-sm"><thead style="color:{muted}"><tr><th class="px-4 py-3">ID</th>{#each sortableHeaders as h}<th class="cursor-pointer px-4 py-3" onclick={()=>toggle(h.key)}>{h.label}</th>{/each}<th class="px-4 py-3">Rev</th><th class="px-4 py-3">Confidence</th></tr></thead><tbody>{#each rows as row}<tr class="cursor-pointer" style="border-top:1px solid {border};color:{text}" onclick={()=>selected=row}><td class="px-4 py-3">{row.id}</td><td class="max-w-52 truncate px-4 py-3">{row.logical_identity_key}</td><td class="px-4 py-3">{row.subject_ref_kind}:{row.subject_ref_id}</td><td class="px-4 py-3">{row.predicate_term_id}</td><td class="px-4 py-3">{row.status}</td><td class="px-4 py-3">{time(row.modify_time)}</td><td class="px-4 py-3">{row.revision}</td><td class="px-4 py-3">{row.confidence ?? '—'}</td></tr>{/each}</tbody></table></div>{/if}</div>
	{#if selected}<div class="rounded-xl p-5" style="background:{card};border:1px solid {border}"><div class="flex justify-between"><h3 style="color:{text};font-weight:600">Assertion #{selected.id} · {selected.status}</h3><button onclick={()=>selected=null} style="color:{muted}">Close</button></div><pre class="mt-3 max-h-72 overflow-auto rounded p-3 text-xs" style="background:{surface};color:{text}">{json(selected)}</pre><div class="mt-3 flex flex-wrap gap-2"><button onclick={newRevision} class="rounded px-3 py-2 text-sm" style="background:{accent};color:white">New Revision</button>{#each ['in_review','accepted','rejected','unsupported','superseded'] as to}{#if can(selected,to)}<button disabled={saving} onclick={()=>transition(to)} class="rounded px-3 py-2 text-sm" style="background:{accent};color:white">Mark {to}</button>{/if}{/each}{#if ['candidate','in_review'].includes(selected.status)}<input placeholder="Dependency fingerprint" bind:value={dependency} class="rounded px-2 py-2 text-sm" style="background:{surface};color:{text};border:1px solid {border}" /><button onclick={defer} class="rounded px-3 py-2 text-sm" style="background:{surface};color:{text};border:1px solid {border}">Defer</button>{/if}{#if selected.status==='deferred'}<input placeholder="Changed dependency fingerprint" bind:value={dependency} class="rounded px-2 py-2 text-sm" style="background:{surface};color:{text};border:1px solid {border}" /><button onclick={retry} class="rounded px-3 py-2 text-sm" style="background:{accent};color:white">Retry</button>{/if}</div></div>{/if}
	{#if showCreate}<div class="rounded-xl p-5" style="background:{card};border:1px solid {border}"><h3 style="color:{text};font-weight:600">{form.revision ? `Create Revision ${form.revision + 1}` : 'Create Assertion'}</h3><div class="mt-3 grid gap-3 md:grid-cols-2">{#each [['logical_identity_key','Logical identity'],['subject_ref_id','Subject ID'],['predicate_term_id','Predicate term'],['object_ref_id','Object ID'],['confidence','Confidence'],['raw_text','Raw text']] as f}<label style="color:{muted}">{f[1]}<input bind:value={form[f[0] as keyof typeof form]} class="w-full rounded px-2 py-1.5 text-sm" style="background:{surface};color:{text};border:1px solid {border}" /></label>{/each}<label style="color:{muted}">Subject kind<select bind:value={form.subject_ref_kind} class="w-full rounded px-2 py-1.5 text-sm" style="background:{surface};color:{text};border:1px solid {border}">{#each kinds as k}<option>{k}</option>{/each}</select></label><label style="color:{muted}">Object literal JSON<input bind:value={form.object_literal} placeholder="optional JSON" class="w-full rounded px-2 py-1.5 text-sm" style="background:{surface};color:{text};border:1px solid {border}" /></label></div><div class="mt-3 flex gap-2"><button onclick={create} disabled={saving} class="rounded px-3 py-2 text-sm" style="background:{accent};color:white">Save</button><button onclick={()=>showCreate=false} class="rounded px-3 py-2 text-sm" style="background:{surface};color:{text};border:1px solid {border}">Cancel</button></div></div>{/if}
</div>
