export type CandidateStatus = 'candidate' | 'in_review' | 'accepted' | 'rejected' | 'deferred' | 'superseded';
export type CandidateKind = 'referent' | 'term_association' | 'assertion' | 'occurrence' | 'profile_selection';
export type CandidateMethod = 'explicit_structured' | 'deterministic_source_span' | 'released_mapping' | 'lexical_candidate' | 'semantic_candidate' | 'structural_candidate' | 'human';
export type DecisionCandidate = { id: number; logical_identity_key: string; revision: number; payload_fingerprint: string; candidate_kind: CandidateKind; proposed_payload: unknown; method: CandidateMethod; resolution_outcome?: string; resolution_reason?: string; source_artifact_type?: string; source_artifact_id?: string; input_record_id?: number; source_line_spans?: unknown; confidence?: number; status: CandidateStatus; decision_reason?: string; dependency_fingerprint?: string; superseded_by?: number; resulting_assertion_id?: number; last_seen: string; create_time: string; create_by?: string; modify_time: string; modify_by?: string; reused?: boolean };
export type CandidateFilters = Partial<{ status: string; candidate_kind: string; method: string; logical_identity: string; source_artifact_type: string; source_artifact_id: string; input_record_id: string }>;
async function req<T>(path: string, init?: RequestInit): Promise<T> { const res = await fetch(path, { credentials: 'same-origin', ...init }); const text = await res.text(); let body: any = null; try { body = text ? JSON.parse(text) : null; } catch {} if (!res.ok) throw new Error(body?.error_msg || `HTTP ${res.status}`); return body as T; }
export async function listCandidates(filters: CandidateFilters, page = 1, pageSize = 50) { const q = new URLSearchParams({ page: String(page), page_size: String(pageSize) }); for (const [k, v] of Object.entries(filters)) if (v?.trim()) q.set(k, v.trim()); return req<{ status: boolean; results: DecisionCandidate[]; page: number; page_size: number; total: number }>(`/api/v1/kb/semantic-decision-candidates?${q}`); }
export async function getCandidate(id: number) { return (await req<{ record: DecisionCandidate }>(`/api/v1/kb/semantic-decision-candidates/${id}`)).record; }
export async function createCandidate(input: Partial<DecisionCandidate>) { return (await req<{ record: DecisionCandidate }>('/api/v1/kb/semantic-decision-candidates', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(input) })).record; }
async function action(id: number, name: string, body: unknown) { return (await req<{ record: DecisionCandidate }>(`/api/v1/kb/semantic-decision-candidates/${id}/${name}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) })).record; }
export const transitionCandidate = (id: number, body: { to: string; reason?: string; by?: string }) => action(id, 'transition', body);
export const resolveCandidate = (id: number, body: { outcome: string; reason?: string }) => action(id, 'resolution', body);
export const deferCandidate = (id: number, body: { dependency_fingerprint: string; reason?: string; by?: string }) => action(id, 'defer', body);
export const retryCandidate = (id: number, body: { dependency_fingerprint: string; by?: string }) => action(id, 'retry', body);
export const linkAssertion = (id: number, assertion_id: number) => action(id, 'assertion', { assertion_id });
